### ISSUE TITLE
Issue aggregating CARS : $Z_MAX problem

### ISSUE THREAD

**Issue by ccmoloney** [aodn/aws-wps#239]
Integration tests fail using the current template from geoserver-content and the latest aggregator code.
Might be resolved by upcoming PRs?

Running integration tests against dev-cam stack - which is running the latest aggregator code (i think...).

Aggregation run by integration tests produces the following result:

        <ns1:Exception exceptionCode="AggregationError">
          <ns1:ExceptionText>Exception occurred during aggregation : For input string: "${Z_MAX}"</ns1:ExceptionText>
        </ns1:Exception>

2018-03-06 23:51:16 INFO [main] au.org.emii.aggregator.NetcdfAggregator : Creating output file /mnt/work/3606abbe-cbe1-4b49-80cb-efb9f16e86c0550140373536713522/agg5256284083120138467.nc using /mnt/work/3606abbe-cbe1-4b49-80cb-efb9f16e86c0550140373536713522/downloads/c84566de-db3b-4624-8998-7df79581d698CARS2009_Australia_weekly.nc as a template
java.lang.NumberFormatException: For input string: "${Z_MAX}"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at au.org.emii.aggregator.datatype.DoubleDataType.parse(DoubleDataType.java:27)
at au.org.emii.aggregator.datatype.NumericTypes.parse(NumericTypes.java:51)
at au.org.emii.aggregator.template.TemplateDataset.createNewAttribute(TemplateDataset.java:170)
at au.org.emii.aggregator.template.TemplateDataset.getGlobalAttributes(TemplateDataset.java:140)
at au.org.emii.aggregator.template.TemplateDataset.<init>(TemplateDataset.java:40)
at au.org.emii.aggregator.NetcdfAggregator.add(NetcdfAggregator.java:100)
at au.org.emii.aggregationworker.AggregationRunner.run(AggregationRunner.java:213)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
at au.org.emii.aggregationworker.Application.main(Application.java:12)
2018-03-06 23:51:16 ERROR [main] : Failed aggregation. JobID [3606abbe-cbe1-4b49-80cb-efb9f16e86c0], Callback email [imos-wps-testing@mailinator.com] : For input string: "${Z_MAX}"
java.lang.NumberFormatException: For input string: "${Z_MAX}"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_131]
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_131]
at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_131]
at au.org.emii.aggregator.datatype.DoubleDataType.parse(DoubleDataType.java:27) ~[aggregator-1.0.0.jar:?]
at au.org.emii.aggregator.datatype.NumericTypes.parse(NumericTypes.java:51) ~[aggregator-1.0.0.jar:?]
at au.org.emii.aggregator.template.TemplateDataset.createNewAttribute(TemplateDataset.java:170) ~[aggregator-1.0.0.jar:?]
at au.org.emii.aggregator.template.TemplateDataset.getGlobalAttributes(TemplateDataset.java:140) ~[aggregator-1.0.0.jar:?]
at au.org.emii.aggregator.template.TemplateDataset.<init>(TemplateDataset.java:40) ~[aggregator-1.0.0.jar:?]
at au.org.emii.aggregator.NetcdfAggregator.add(NetcdfAggregator.java:100) ~[aggregator-1.0.0.jar:?]
at au.org.emii.aggregationworker.AggregationRunner.run(AggregationRunner.java:213) [aggregation-worker.jar:?]

**Comment by anguss00** [comment]
Does this occur when the test are run against this template? https://github.com/aodn/aws-wps/blob/master/wps-common/src/main/resources/config/templates.xml

**Comment by ccmoloney** [comment]
Seems to.  My stack definitely using that template.  It is using geoserver-123 for data.  Maybe a mismatch or something?

**Comment by anguss00** [comment]
Cool, might have to VIT this issue as it will block release for sure @ccmoloney

**Comment by ccmoloney** [comment]
Removing.  Dev that requires changes to the templates.xml file will need to point to a file hosted somewhere in S3 or a github branch.

**Comment by ccmoloney** [comment]
Closing.  The Z_MAX problem appears to have been caused by an out of date templates.xml file residing in the aws-wps wps-common project.  To avoid this confusion in the future we have removed that copy - and developers can source the templates.xml from the geoserver-config repository.
